### ISSUE TITLE
questions from newcomer

### ISSUE THREAD

**Issue by jangorecki** [hybris-mobian/meta#1]
Thank you for creating this repository.
I don't know much about mobian and hybris-mobian. I landed here because I am going to be owner of pro1x, and it was mentioned that it will support debian-like system. This is very good news because of apt packages that debian (ubuntu and other distro) are using.

- As a person who don't know anything about mobian/hybris-mobian, I got confused at start by the fact that there are two organisations, named quite the same, and they do quiet the same stuff, just for a different device. Could you please clarify, how hybris-mobian is different from mobian, and why it is a separate org rather than just another project inside existing org?
- I would kindly ask for a dedicated article on making stock pro1x a dualboot device for running hybris-mobian as a secondary OS. My device will come with LineageOS but ideally would be to have an article that will work for other stock OSes so other newcomers can benefit from it.
- Is battery life not a problem when running hybris-mobian? Based on the experience of Purism smartphone running debian-like OS, it seems to be a big issue. Without having that resolved the devices losses its mobility as it has to be continuously charged.

Thank you for your time and development!

**Comment by g7** [comment]
Hello!

> As a person who don't know anything about mobian/hybris-mobian, I got confused at start by the fact that there are two organisations, named quite the same, and they do quiet the same stuff, just for a different device. Could you please clarify, how hybris-mobian is different from mobian, and why it is a separate org rather than just another project inside existing org?

[libhybris](https://en.wikipedia.org/wiki/Hybris_(software)) is a library that allows running Android device drivers and other platform bits on "standard" distributions running glibc (such as Debian).
Many "Linux on mobile" efforts in the past decade used libhybris in one way or another. For example Sailfish OS, Ubuntu Touch, LuneOS, etc.


Pinephone and the Librem 5 are different though. They don't require the Android kernel, the various proprietary blobs, drivers and the underlying platform an Android device needs. Thus, the distributions developed on those devices can't be installed on Android phones as-is.

The goal of the hybris-mobian project is to be able to run Mobian on Android phones (such as the Pro1). leveraging libhybris, [Halium](https://halium.org/), etc.

hybris-mobian sits "on top" of mobian, so their packages are used if not strictly needed (you can look at this very same github organization to have an idea on our modifications and patches).

Mobian itself sits "on top" of Debian, so you'll have access to standard Debian repository as well.

> I would kindly ask for a dedicated article on making stock pro1x a dualboot device for running hybris-mobian as a secondary OS. My device will come with LineageOS but ideally would be to have an article that will work for other stock OSes so other newcomers can benefit from it.

Once the Pro1 multiboot stuff they're working on is ready, sure thing.

> Is battery life not a problem when running hybris-mobian? Based on the experience of Purism smartphone running debian-like OS, it seems to be a big issue. Without having that resolved the devices losses its mobility as it has to be continuously charged.

Well, currently battery life is not something we're focusing on, we need to make most stuff work first :smile: 

I use my device only for development at the moment thus I can't really comment on the battery life. I guess it's on par as my Pinephone. But keep in mind that we haven't really looked at power management stuff as of now.
Since we are using the underlying Android stuff perhaps we could achieve something decent, that's my personal goal at least (as I would like to use hybris-mobian as my daily driver).

**Comment by jangorecki** [comment]
Thank you for answers all my questions such in details. It is now more clear. I think that using android kernel may actually bring some more battery life, comparing to Pinephone or Librem. As all my questions has been answered I will close this issue. Looking forward to try hybris-mobian in future.
